# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-07 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('transaction_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
