# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-07 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 17, 4, 38, 94258), null=True),
        ),
    ]
