# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20220507_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
