# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owned_by', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='disabled', max_length=10)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
